# Generated by Django 3.2.20 on 2023-10-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0003_auto_20231015_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
    ]
